name    'rcoleman-puppet_module'
version '0.0.1'
source  'git@github.com:rcoleman/puppet_module_provider.git'
author  'pvande / Puppet Labs'
license 'Apache License 2.0'
summary 'puppet_module provider for the package type'
description 'Manage Puppet Forge modules as Puppet resources with this provider'
project_page 'https://github.com/rcoleman/puppet_module_provider'
